### ISSUE TITLE
Tests test_more_than_7_attr_creation_track_order and test_bool_slicing_length_one_dim fail in the test suite

### ISSUE THREAD

**Issue by mcepl** [h5netcdf/h5netcdf#179] opened 2022-07-29 17:50 UTC
#### What happened:

While packaging new version of h5netcdf for openSUSE we run the test suite, and these two tests failed for us:

```
[   32s] =================================== FAILURES ===================================
[   32s] _______________ test_more_than_7_attr_creation_track_order[True] _______________
[   32s] 
[   32s] tmp_local_netcdf = '/tmp/pytest-of-abuild/pytest-0/test_more_than_7_attr_creation2/testfile.nc'
[   32s] track_order = True
[   32s] 
[   32s]     @pytest.mark.parametrize("track_order", [False, True])
[   32s]     def test_more_than_7_attr_creation_track_order(tmp_local_netcdf, track_order):
[   32s]         if track_order:
[   32s]             expected_errors = pytest.raises(KeyError)
[   32s]         else:
[   32s]             # We don't expect any errors. This is effectively a void context manager
[   32s]             expected_errors = memoryview(b"")
[   32s]     
[   32s]         with expected_errors:
[   32s]             with h5netcdf.File(tmp_local_netcdf, "w", track_order=track_order) as h5file:
[   32s]                 for i in range(100):
[   32s]                     h5file.attrs[f"key{i}"] = i
[   32s] >                   h5file.attrs[f"key{i}"] = 0
[   32s] E                   Failed: DID NOT RAISE <class 'KeyError'>
[   32s] 
[   32s] h5netcdf/tests/test_h5netcdf.py:1613: Failed
[   32s] _______________________ test_bool_slicing_length_one_dim _______________________
[   32s] 
[   32s] tmp_local_netcdf = '/tmp/pytest-of-abuild/pytest-0/test_bool_slicing_length_one_d0/testfile.nc'
[   32s] 
[   32s]     def test_bool_slicing_length_one_dim(tmp_local_netcdf):
[   32s]         # see https://github.com/h5netcdf/h5netcdf/issues/23
[   32s]         with h5netcdf.File(tmp_local_netcdf, "w") as ds:
[   32s]             ds.dimensions = {"x": 1, "y": 2}
[   32s]             v = ds.create_variable("hello", ("x", "y"), "float")
[   32s]             v[:] = np.ones((1, 2))
[   32s]     
[   32s]         bool_slice = np.array([1], dtype=bool)
[   32s]     
[   32s]         # works for legacy API
[   32s]         with legacyapi.Dataset(tmp_local_netcdf, "a") as ds:
[   32s]             data = ds["hello"][bool_slice, :]
[   32s]             np.testing.assert_equal(data, np.ones((1, 2)))
[   32s]             ds["hello"][bool_slice, :] = np.zeros((1, 2))
[   32s]             data = ds["hello"][bool_slice, :]
[   32s]             np.testing.assert_equal(data, np.zeros((1, 2)))
[   32s]     
[   32s]         # should raise for h5py >= 3.0.0
[   32s]         with h5netcdf.File(tmp_local_netcdf, "r") as ds:
[   32s]             if version.parse(h5py.__version__) >= version.parse("3.0.0"):
[   32s]                 error = "Indexing arrays must have integer dtypes"
[   32s]                 with pytest.raises(TypeError) as e:
[   32s] >                   ds["hello"][bool_slice, :]
[   32s] E                   Failed: DID NOT RAISE <class 'TypeError'>
[   32s] 
[   32s] h5netcdf/tests/test_h5netcdf.py:1703: Failed
[   32s] =========================== short test summary info ============================
[   32s] SKIPPED [20] h5netcdf/tests/test_h5netcdf.py:40: h5pyd package not available
[   32s] SKIPPED [1] h5netcdf/tests/test_h5netcdf.py:1546: h5py bug with track_order prevents editing with netCDF4
[   32s] SKIPPED [1] h5netcdf/tests/test_h5netcdf.py:1577: h5py bug with track_order
[   32s] =================== 2 failed, 69 passed, 22 skipped in 3.22s ===================
[
```
[Complete build log](https://github.com/h5netcdf/h5netcdf/files/9222221/_log.txt) with the list of all packages used and steps taken to build the package.

#### What you expected to happen:
Whole test suite should pass.

#### Version

1.0.1 (tarball from PyPI)

**Comment by kmuehlbauer** [comment] 2022-07-29 18:32
Thanks for raising this, @mcepl .

I'll have a look into this the next days.

I can't immediately see any problems with the dependencies. But is there any reason to work with hdf5 1.10 version line instead of 1.12? 

The error might be connected with that version, as we do not test against hdf5 1.10.

**Comment by mcepl** [comment] 2022-07-29 18:50
Ah, that might be a problem. Let me update that as well.

**Comment by drew-parsons** [comment] 2022-08-02 09:02
Debian has also just started hitting this error, after upgrading h5py to 3.7.0.  Full test log at https://ci.debian.net/data/autopkgtest/testing/amd64/p/python-h5netcdf/24248189/log.gz

Debian also uses hdf5 1.10. I don't know why we haven't updated to hdf5 1.12 yet.  But in any case the h5netcdf test failure seems to be triggered by h5py 3.7.0. It's still [passing](https://ci.debian.net/data/autopkgtest/testing/amd64/p/python-h5netcdf/24254618/log.gz) with run with h5py 3.6.0 (still with hdf5 1.10).

**Comment by kmuehlbauer** [comment] 2022-08-02 09:05
@drew-parsons Thanks. We need to find the root cause. I'll try to reproduce this locally first. Any guidance on your test setup @mcepl, @drew-parsons?

**Comment by kmuehlbauer** [comment] 2022-08-02 09:21
@mcepl @drew-parsons My bad, I'm deeply sorry. :disappointed: I've worked on current main branch where @hmaarrfk and I already fixed that two errors which indeed stem from new h5py version 3.7.0.

I'll have a release out today. Sorry for the confusion.

**Comment by kmuehlbauer** [comment] 2022-08-02 09:35
@mcepl @drew-parsons h5netcdf 1.0.2 with the fixes is available on PyPI.

**Comment by mcepl** [comment] 2022-08-02 16:48
Yes, it works fine, thank you.

**Comment by kmuehlbauer** [comment] 2022-08-02 17:12
Thanks for confirming @mcepl. Let's see if it works on Debian, too. I'll close then.

**Comment by hmaarrfk** [comment] 2022-08-03 11:05
@kmuehlbauer worked with h5py to fix things only to cause more problems!!!! Thank you all for being patient!

**Comment by drew-parsons** [comment] 2022-08-03 12:06
If there are known ongoing problems then if you like I can apply just the targetted h5py patch to Debian, not the whole 1.0.2 release.

**Comment by kmuehlbauer** [comment] 2022-08-03 12:16
I think you are safe to apply 1.0.2 There is one other change with regard to boolean indexing which also started to work with h5py 3.7.0.

**Comment by kmuehlbauer** [comment] 2022-08-03 12:17
So essentially the 1.0.2 consists only of two fixes for the two errors you experienced.

**Comment by drew-parsons** [comment] 2022-08-03 12:19
ok.  With commit 68d125a on its own, it cleared the test_bool_slicing_length_one_dim error. But it still left the other error in place,
```
________________________________________________________________________________ test_more_than_7_attr_creation_track_order[True] _________________________________________________________________________________

tmp_local_netcdf = '/tmp/pytest-of-drew/pytest-7/test_more_than_7_attr_creation2/testfile.nc', track_order = True

    @pytest.mark.parametrize("track_order", [False, True])
    def test_more_than_7_attr_creation_track_order(tmp_local_netcdf, track_order):
        if track_order:
            expected_errors = pytest.raises(KeyError)
        else:
            # We don't expect any errors. This is effectively a void context manager
            expected_errors = memoryview(b"")
    
>       with expected_errors:
E       Failed: DID NOT RAISE <class 'KeyError'>

tests/test_h5netcdf.py:1609: Failed
```
Should this second error be fixed in the full 1.0.2 code?

**Comment by drew-parsons** [comment] 2022-08-03 12:21
Ah wait I see, the other one would be fixed in commit d37661010.

**Comment by kmuehlbauer** [comment] 2022-08-03 12:42
@drew-parsons, @mcepl Just a little heads up. Since version 1.0 gets more and more applied I assume we might get more regression issues, also as other upstream libs (h5py, hdf5) release new versions. There also have been some major rewrites before h5netcdf 1.0 which add to this.

I'll try to not let issues pile up, but try to fix and release patches when I see fit. It's appreciated if you continue to open issues here, if any problems arise on your side. Thanks.

**Comment by mcepl** [comment] 2022-08-03 12:45
Sure, I won’t stop bothering you ;).

**Comment by kmuehlbauer** [comment] 2022-08-03 13:58
Great, it looks like it works on debian too. The bug is closed over there. So closing here.

**Closed by kmuehlbauer** 2022-08-03 13:58 UTC

**Comment by kmuehlbauer** [comment] 2023-01-12 07:51
See upstream https://github.com/HDFGroup/hdf5/issues/1388 for details.
