### ISSUE TITLE
Files written by h5netcdf cannot be edited by netcdf4-python

### ISSUE THREAD

**Issue by hmaarrfk** [h5netcdf/h5netcdf#128] opened 2022-01-09 13:29 UTC
#### What happened:

Files written by h5netcdf cannot be edited by netcdf4-python. It would be good if they could be. I believe the following patch is needed. Would you like me to make the Pull Request?

#### MCVE Code Sample

```python
import xarray as xr
import numpy as np
dataset = xr.DataArray(
    data=np.zeros((3, 3)),
    name="my_data"
)

engine = "h5netcdf"
# engine = "netcdf4"
dataset.to_netcdf("test.nc", engine=engine, format="NETCDF4")

import netCDF4
nc = netCDF4.Dataset("test.nc", mode="a")
```
```python
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_367089/2679834096.py in <module>
      1 import netCDF4
----> 2 nc = netCDF4.Dataset("test.nc", mode="a")

src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -103] NetCDF: Can't write file: b'test.nc'
```

#### Expected Output
That it works.

#### Version

<details><summary>Output of <tt>print(h5py.version.info, f"\nh5netcdf {h5netcdf.__version__}")</tt></summary>

Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.12.1
Python  3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.5
cython (built with) 0.29.24
numpy (built against) 1.19.5
HDF5 (built against) 1.12.1
 
h5netcdf 0.12.0

</details>

<details><summary>Suggested patch</summary>

```python
diff --git a/h5netcdf/core.py b/h5netcdf/core.py
index b68e3f5..5994928 100644
--- a/h5netcdf/core.py
+++ b/h5netcdf/core.py
@@ -462,7 +462,7 @@ class Group(Mapping):
     def _create_child_group(self, name):
         if name in self:
             raise ValueError("unable to create group %r (name already exists)" % name)
-        self._h5group.create_group(name)
+        self._h5group.create_group(name, track_order=True)
         self._groups[name] = self._group_cls(self, name)
         return self._groups[name]
 
@@ -474,7 +474,7 @@ class Group(Mapping):
 
     def create_group(self, name):
         if name.startswith("/"):
-            return self._root.create_group(name[1:])
+            return self._root.create_group(name[1:], track_order=True)
         keys = name.split("/")
         group = self
         for k in keys[:-1]:
@@ -789,15 +789,15 @@ class File(Group):
                             "opening urls: {}".format(path)
                         )
                     try:
-                        with h5pyd.File(path, "r") as f:  # noqa
+                        with h5pyd.File(path, "r", track_order=True) as f:  # noqa
                             pass
                         self._preexisting_file = True
                     except IOError:
                         self._preexisting_file = False
-                    self._h5file = h5pyd.File(path, mode, **kwargs)
+                    self._h5file = h5pyd.File(path, mode, track_order=True, **kwargs)
                 else:
                     self._preexisting_file = os.path.exists(path) and mode != "w"
-                    self._h5file = h5py.File(path, mode, **kwargs)
+                    self._h5file = h5py.File(path, mode, track_order=True, **kwargs)
             else:  # file-like object
                 if version.parse(h5py.__version__) < version.parse("2.9.0"):
                     raise TypeError(
@@ -806,7 +806,7 @@ class File(Group):
                     )
                 else:
                     self._preexisting_file = mode in {"r", "r+", "a"}
-                    self._h5file = h5py.File(path, mode, **kwargs)
+                    self._h5file = h5py.File(path, mode, track_order=True, **kwargs)
         except Exception:
             self._closed = True
             raise
```
</details>

**Comment by kmuehlbauer** [comment] 2022-01-09 14:38
@hmaarrfk Thanks for investigating and reporting this issue.

Could you please add the netcdf-c and netcdf-python versions, so we are on the same page for testing this. Do you happen to know, if this is a regression in 0.12.0?

Using `track_order=True` changes the iter behaviour from alphanumeric to creation order. I'm wondering if this is some speciality xarray is relying on and some subtle change which might have been introduced in the latest h5netcdf versions.

I'll try to get to the bottom of this.

**Comment by hmaarrfk** [comment] 2022-01-09 15:27
This is the line in particular that is causing things to fail:

https://github.com/Unidata/netcdf-c/blob/988e771a9ed99619c2e3261aea81f127dd7fa3d8/libhdf5/hdf5open.c#L2797

**Comment by hmaarrfk** [comment] 2022-01-09 15:29
git blame shows that this was true for at least 3 years.

Even then, the last change was for a massive cleanup.

**Comment by hmaarrfk** [comment] 2022-01-09 15:35
```
$ mamba list netcdf
# packages in environment at /home/mark/mambaforge/envs/dev:
#
# Name                    Version                   Build  Channel
h5netcdf                  0.12.0                    dev_0    <develop>
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
netcdf4                   1.5.8                     dev_0    <develop>
```

**Comment by hmaarrfk** [comment] 2022-01-09 15:39
I'm sorry I provided an example with xarray. I knew I should have done one with h5netcdf bare without the added dependency.

Here is the minimum reproducible example:

```python
import h5netcdf
import netCDF4
with h5netcdf.File('test.nc', 'w') as f:
    pass
with netCDF4.Dataset("test.nc", mode="a") as f:
    pass
```

```python
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_385617/3181076220.py in <module>
      3 with h5netcdf.File('test.nc', 'w') as f:
      4     pass
----> 5 with netCDF4.Dataset("test.nc", mode="a") as f:
      6     pass

src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

src/netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -103] NetCDF: Can't write file: b'test.nc'
```

**Comment by hmaarrfk** [comment] 2022-01-09 15:52
I also confirmed that this is also the case for `h5netcdf` version `0.11.0`

**Comment by hmaarrfk** [comment] 2022-01-09 16:12
The netcdf4 standard requires that the creation order be maintained. They also specify that the file has to be created with creation order specified. Therefore, I think this should be considered a bug within `h5netcdf`.

![image](https://user-images.githubusercontent.com/90008/148690596-21b708be-a3a4-4dc0-8c9c-710c95002d33.png)
https://docs.unidata.ucar.edu/netcdf-c/current/file_format_specifications.html

**Comment by hmaarrfk** [comment] 2022-01-09 16:25
From `h5py` source
https://github.com/h5py/h5py/blob/aa31f03bef99e5807d1d6381e36233325d944279/h5py/_hl/group.py#L65
![image](https://user-images.githubusercontent.com/90008/148691082-da8f92e4-03a9-4e06-a180-cc09a7dce963.png)

I think my original patch missed to add the `track_order=True` keyword argument to a few `create_dataset` calls, but I'm going to make a PR now that enforces all of this.

**Comment by kmuehlbauer** [comment] 2022-01-09 16:32
@hmaarrfk Could you please have a look at this discussion (netcdf-c):

https://github.com/Unidata/netcdf-c/issues/2054

It seems that it was tried to enable opening for append regardless of the tracking_order. But it did not find it's way into the latest release.

So this "feature" prevented files created using `h5netcdf` to be changed using netcdf-c/netcdf4-python. I'm wondering why this did not surface much earlier.

We might use h5.get_config().track_order to set it globally, then?

**Comment by kmuehlbauer** [comment] 2022-01-09 16:37
@hmaarrfk Sorry, missed to explicitely welcome a PR. Yes, please!

**Comment by hmaarrfk** [comment] 2022-01-09 16:39
How would you like the deprecation cycle to go? Do you want to have a parameter that enables `track_order` to be set?

Before I go off and hack, do you have a suite of regression tests that ensure that you can still open old files?

**Comment by kmuehlbauer** [comment] 2022-01-09 16:53
@hmaarrfk A first test writing with `track_order=False` and reading with `track_order=True` gives no problems. It looks like `h5netcdf` is track_order agnostic somehow. 

It would be good to parameterize it, with default to `track_order=True`. Not sure if we need a deprecation cycle if this has no effects. The only effect I can think of is that some objects are repr'd in another order. But if this new ordering is in line with Python `dict` I would just give it a go. But I'd like to hear @shoyer's suggestions how to proceed here.


Sure adding tests for checking different read/write combinations would be good.

**Comment by hmaarrfk** [comment] 2022-01-09 17:31
Let me know if you think anything is missing from
https://github.com/h5netcdf/h5netcdf/pull/129

Happy to hold off on any discussion there while we wait for shoyer to chime in here.

**Comment by hmaarrfk** [comment] 2022-01-09 20:44
To summarize the issue you pointed to:

netCDF4 wants the track_order parameter of the h5py constructors to be true
though this might be getting relaxed in a more recent version of the standard, it seems like it is a little far away for now.

**Comment by shoyer** [comment] 2022-01-10 03:02
Why would an h5netcdf want to write a file without tracking order?

If we can't come up with a use-case, then we should treat this as a bug and just fix it.

**Comment by hmaarrfk** [comment] 2022-01-10 03:52
The issue cross referenced comes up with one
https://github.com/Unidata/netcdf-c/issues/2054

It seems that netcdf is considering updating their stance. However, I fear that the issue will only pop up in multi-threaded workloads.

I don't think it is possible to start tracking within a group if it was disabled at the start.
The suggested patch enables compatibility with older datasets (tracking will remain disabled) while enabling it on newer files.

**Comment by shoyer** [comment] 2022-01-10 04:17
This seems like the right fix then. I'm mostly just questioning whether we need the new keyword argument, or if it would be better to always turn it on.

**Comment by hmaarrfk** [comment] 2022-01-10 04:31
We could remove the keyword argument if you prefer. It would be trivial to add back in the future.

**Comment by shoyer** [comment] 2022-01-10 04:53
Yeah, I don't see a reason to add it, if it's required for writing files there work with netcdf-C

**Comment by kmuehlbauer** [comment] 2022-01-10 06:33
Thanks @shoyer, @hmaarrfk, that looks like a way forward.

I'd suggest then to not only remove `track_order` as new positional keyword argument, but go one step further. We should test if it is fed via `**kwargs` (which users might do) and raise an informative error if `track_order=False`. This can later be relaxed to align with new developments in netcdf-c/netcdf4-python.

**Comment by kmuehlbauer** [comment] 2022-01-11 06:45
@hmaarrfk see #131. Closing this as resolved. Thanks!

**Closed by kmuehlbauer** 2022-01-11 06:45 UTC
Labels: bug

**Comment by kmuehlbauer** [comment] 2022-01-12 06:54
@hmaarrfk `h5netcdf 0.13.0` with the fix is out on PyPI.

**Comment by hmaarrfk** [comment] 2022-01-12 08:05
awesome!

**Comment by kmuehlbauer** [comment] 2023-01-12 07:52
See upstream https://github.com/HDFGroup/hdf5/issues/1388 for details.
